const ZOOM_DEFAULT = 10;
const COORDS_DIGITS = 5;
const DECIMAL_PLACES = 5;

const DEFAULT_COORDS = {
  lat: 35.68256,
  lng: 139.75114
};

export {ZOOM_DEFAULT, COORDS_DIGITS, DECIMAL_PLACES, DEFAULT_COORDS};
